#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-powermock
Version  : 1.6.4
Release  : 1
URL      : https://github.com/powermock/powermock/archive/powermock-1.6.4.tar.gz
Source0  : https://github.com/powermock/powermock/archive/powermock-1.6.4.tar.gz
Source1  : https://repo1.maven.org/maven2/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.jar
Source2  : https://repo1.maven.org/maven2/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.pom
Source3  : https://repo1.maven.org/maven2/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.jar
Source4  : https://repo1.maven.org/maven2/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-powermock-data = %{version}-%{release}

%description
![PowerMock](powermock.png)
[![Build Status](https://travis-ci.org/jayway/powermock.svg)](https://travis-ci.org/jayway/powermock)

%package data
Summary: data components for the mvn-powermock package.
Group: Data

%description data
data components for the mvn-powermock package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.jar
/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.jar
/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.pom
