#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-powermock
Version  : 1.6.4
Release  : 4
URL      : https://github.com/powermock/powermock/archive/powermock-1.6.4.tar.gz
Source0  : https://github.com/powermock/powermock/archive/powermock-1.6.4.tar.gz
Source1  : https://repo1.maven.org/maven2/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.jar
Source2  : https://repo1.maven.org/maven2/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.pom
Source3  : https://repo1.maven.org/maven2/org/powermock/powermock-api-support/1.6.2/powermock-api-support-1.6.2.jar
Source4  : https://repo1.maven.org/maven2/org/powermock/powermock-api-support/1.6.2/powermock-api-support-1.6.2.pom
Source5  : https://repo1.maven.org/maven2/org/powermock/powermock-api/1.6.2/powermock-api-1.6.2.pom
Source6  : https://repo1.maven.org/maven2/org/powermock/powermock-core/1.6.2/powermock-core-1.6.2.jar
Source7  : https://repo1.maven.org/maven2/org/powermock/powermock-core/1.6.2/powermock-core-1.6.2.pom
Source8  : https://repo1.maven.org/maven2/org/powermock/powermock-module-junit4-common/1.6.2/powermock-module-junit4-common-1.6.2.jar
Source9  : https://repo1.maven.org/maven2/org/powermock/powermock-module-junit4-common/1.6.2/powermock-module-junit4-common-1.6.2.pom
Source10  : https://repo1.maven.org/maven2/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.jar
Source11  : https://repo1.maven.org/maven2/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.pom
Source12  : https://repo1.maven.org/maven2/org/powermock/powermock-modules/1.6.2/powermock-modules-1.6.2.pom
Source13  : https://repo1.maven.org/maven2/org/powermock/powermock-reflect/1.6.2/powermock-reflect-1.6.2.jar
Source14  : https://repo1.maven.org/maven2/org/powermock/powermock-reflect/1.6.2/powermock-reflect-1.6.2.pom
Source15  : https://repo1.maven.org/maven2/org/powermock/powermock/1.6.2/powermock-1.6.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-powermock-data = %{version}-%{release}

%description
![PowerMock](powermock.png)
[![Build Status](https://travis-ci.org/jayway/powermock.svg)](https://travis-ci.org/jayway/powermock)

%package data
Summary: data components for the mvn-powermock package.
Group: Data

%description data
data components for the mvn-powermock package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-support/1.6.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-support/1.6.2/powermock-api-support-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-support/1.6.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api-support/1.6.2/powermock-api-support-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api/1.6.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-api/1.6.2/powermock-api-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-core/1.6.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-core/1.6.2/powermock-core-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-core/1.6.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-core/1.6.2/powermock-core-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.2
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.2/powermock-module-junit4-common-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.2/powermock-module-junit4-common-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-modules/1.6.2
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-modules/1.6.2/powermock-modules-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-reflect/1.6.2
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-reflect/1.6.2/powermock-reflect-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-reflect/1.6.2
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock-reflect/1.6.2/powermock-reflect-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock/1.6.2
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/powermock/powermock/1.6.2/powermock-1.6.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.jar
/usr/share/java/.m2/repository/org/powermock/powermock-api-easymock/1.6.2/powermock-api-easymock-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock-api-support/1.6.2/powermock-api-support-1.6.2.jar
/usr/share/java/.m2/repository/org/powermock/powermock-api-support/1.6.2/powermock-api-support-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock-api/1.6.2/powermock-api-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock-core/1.6.2/powermock-core-1.6.2.jar
/usr/share/java/.m2/repository/org/powermock/powermock-core/1.6.2/powermock-core-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.2/powermock-module-junit4-common-1.6.2.jar
/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4-common/1.6.2/powermock-module-junit4-common-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.jar
/usr/share/java/.m2/repository/org/powermock/powermock-module-junit4/1.6.2/powermock-module-junit4-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock-modules/1.6.2/powermock-modules-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock-reflect/1.6.2/powermock-reflect-1.6.2.jar
/usr/share/java/.m2/repository/org/powermock/powermock-reflect/1.6.2/powermock-reflect-1.6.2.pom
/usr/share/java/.m2/repository/org/powermock/powermock/1.6.2/powermock-1.6.2.pom
